included:
  - Sources
  - Tests

excluded:
  - .build

disabled_rules:
  - trailing_comma
  - identifier_name
  - line_length
  - type_body_length
  - file_length
  - function_body_length

opt_in_rules:
  - empty_count
  - force_unwrapping
  - implicitly_unwrapped_optional
  - private_outlet
  - private_action

force_cast: warning
force_try: warning
force_unwrapping: warning
